version: "3.8" 

services:
  app:
    build:
      context: ..                       
      dockerfile: docker/Dockerfile     
    ports:
      - 8001:8000
      - 10003:10005
    volumes:
      - ../:/usr/src/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - ../.env

